source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/WPMedia/Podspecs.git'

inhibit_all_warnings!

pod 'WPObjectMapper', :path => '..'
pod 'WPFaker', '~> 0.0.5'

target 'WPObjectMapperExampleTests', :exclusive => true do
    pod 'WPFaker', '~> 0.0.5'
end